# Generated by Django 5.0.7 on 2024-07-16 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=10, unique=True)),
                ('upc', models.CharField(max_length=14, unique=True)),
                ('description', models.TextField()),
                ('quantity_on_hand', models.IntegerField()),
                ('quantity_on_order', models.IntegerField()),
                ('order_point', models.IntegerField()),
                ('date_of_last_purchase', models.DateField()),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('replacement_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('current_month_sales', models.IntegerField()),
                ('previous_12_month_sales', models.IntegerField()),
            ],
        ),
    ]
